# Generated by Django 3.1.6 on 2021-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190907_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='skype_url',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='twitter_url',
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
